name: build-apk
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "**/*.gradle*"
      - "**/src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Install Gradle 8.7 and use the CLI directly (no wrapper)
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      - name: Show modules
        run: gradle -p Ashboxcompanion projects

      - name: Build debug APK (verbose)
        run: gradle -p Ashboxcompanion --no-daemon --stacktrace --info assembleDebug

      - name: Upload APK artifact(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            Ashboxcompanion/**/build/outputs/apk/**/debug/*.apk
            Ashboxcompanion/**/build/outputs/**/*-debug.apk
