name: build-apk

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "**/*.gradle*"
      - "**/src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
       - name: Install Android packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      # Use a modern Gradle to generate the wrapper (your error was old Gradle)
      - name: Setup Gradle 8.7 (no wrapper yet)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Gradle wrapper (8.7)
        run: gradle wrapper --gradle-version 8.7

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: "**/build/outputs/apk/**/debug/*.apk"
